### PR TITLE
[Work In Progress] Python 3 conversion

### PR DESCRIPTION
**Pull request by dralley**
This series of commits will break backwards compatibility with Python 2.

It is currently broken due to issues w/ how bytes are processed in ```daemon.py``` (using bytestrings).  ```python3 syncthing-gtk.py --verbose --debug``` shows a few errors.

I'm probably a little out of my depth working in that code, but I'll give it a shot.

If you still aren't ready to take the leap, I can discontinue it for now and hopefully it will still make things easier later on.

Minor suggestion: bytestrings probably is not the best way to do async network IO, it might be better (both in style and performance) to use something like ```io.BytesIO``` (https://docs.python.org/3/library/io.html).  Strings are immutable so every time you append to one, it's really allocating a new larger string and copying the whole thing over.

### CODE REVIEW

**Comment by kozec** [comment]
I have to admit, I don't follow how we come from me expressing that I can't support code that doesn't work with Py2 to "taking the leap" :D I really can't code with py3, I don't know the language and differences I saw doesn't leave me confident enough to "wing it" and hope for best.

About bytestrings, this was only way how to communicate with GLib and Gio back when I originally coded that module. It is possible it's not needed anymore, assuming there is no poor soul running something like xUbuntu 14.04 left.

**Comment by dralley** [comment]
@kozec OK, but that will not be tenable long-term.

https://fedoraproject.org/wiki/Changes/Mass_Python_2_Package_Removal

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Comment by dralley** [comment]
@kozec You've got about one year before distros start dropping Python 2 packages entirely

https://fedoraproject.org/wiki/Changes/RetirePython2

**Pull request closed without merging**
