### PR TITLE
daemonprocess: Use more compatible syntax for `nice`

### PR DESCRIPTION
**Pull request by Somasis**
On systems with non-GNU coreutils, `nice` usually expects to have `-n %s` passed to it, as the way
to specify the priority desired, rather than `-%s` which doesn't work on some implementations.

### CODE REVIEW

**Comment by kozec** [comment]
Sounds reasonable, but this
```python
Popen([ "nice", "-n %s" % self.priority ], stdout=PIPE)
```
will probably not work. Each argument has to be it's own list item, otherwise nice will receive it as one, long argument '-n 19'.

**Comment by Somasis** [comment]
It worked for me... but I'll change it.

**Comment by kozec** [comment]
Sorry about merging it so late, github apparently doesn't send notifications about commits and I noticed it just now :(

**Comment by Somasis** [comment]
All good. Thanks for merging.

**Pull request merged**
