### PR TITLE
Python 3 port

### PR DESCRIPTION
**Pull request by Salamandar**
There are still bugs, but this project needed a Python 3 port. That's starting now I guess.

I had to port to spaces because Python was complaining about mixed spaces and tabs. And spaces are considered as the preferred tabulation system in Py3.

### CODE REVIEW

**Comment by phw** [comment]
Just for reference, PR https://github.com/syncthing/syncthing-gtk/pull/475 was a previous attempt at this. I haven't compared, but it might be worth looking there and taking things that probably are missing in this PR.

Relevant issue is https://github.com/syncthing/syncthing-gtk/issues/487

**Comment by Salamandar** [comment]
I think you will have to make a "python3" branch where all our PR will be merged, so that it doesn't need a single big PR.

**Comment by dralley** [comment]
Feel free to reuse my work in the aforementioned PR, I don't mind.  I tried to keep each individual change in it's own commit.

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
