### PR TITLE
Working Python 3 support, plus Fedora RPM packaging

### PR DESCRIPTION
**Pull request by Rudd-O**
WIth this, Syncthing-GTK actually _works_ on Fedora, instead of crashing and burning.

### CODE REVIEW

**Comment by Rudd-O** [comment]
How long do you think it will take to get this PR merged?

I'm satisfactorily running Syncthing-GTK with this.

Would you consider relinquishing maintainership?

Thanks.

**Comment by Rudd-O** [comment]
Hello?   Nothing here?

**Comment by Newbytee** [comment]
@kozec?

**Comment by hrehfeld** [comment]
I took the liberty to open an organization for this, maybe we can maintain a fork there, even if temporary? https://github.com/syncthing-gtk/syncthing-gtk @Rudd-O is invited as an owner.

**Comment by tengwar** [comment]
Thanks!

README.md also needs updating, e.g. the dependencies section or the fact that it's no longer in Arch repos.

**Comment by Rudd-O** [comment]
https://github.com/syncthing-gtk/syncthing-gtk has this branch merged and more fixe.s

I am closing this PR and people are invited to abandon this repository as upstream.

**Pull request closed without merging**
