### PR TITLE
Draft of natively included Debian control directory

### PR DESCRIPTION
**Pull request by acolomb**
This is **not actually ready to pull**, but just a draft of what I had in mind concerning #154.

It basically mirrors the great packaging work of Alin Andrei for Webupd8, with some additional fixes to make the package build. It's my first attempt at building a Debian package, so don't take this as a definite solution.

Having the `debian/` directory upstream is probably not bad, but also a little unusual. I have seen people suggest to keep the packaging related stuff in a separate branch (now assumed to be called `debian`). For each release tag, one would then create another packaging-specific release branch (`debian-0.7.123`), merge in the new release, make any necessary modifications to the control files and Debian changelog, then merge it back to the packaging branch and tag it as a new debian release. These releases would then be built and uploaded to some 'official' repository.

### CODE REVIEW

**Comment by kozec** [comment]
To be honest, unless it's absolutely required, I'd rather _not_ have debian/ directory. My idea of packaging is one script ran on checked out source that doesn't change anything and that doesn't seems to be possible with standard Debian methods.

**Comment by acolomb** [comment]
I fully understand your position, however I don't see how a Debian package can be sensibly built from sources without using the specialized tools. They contain a huge bunch of checks to make sure the package meets policy requirements and will be installable cleanly.

Back to the original proposal, I think the only "upstream" change required here is to provide a switch for excluding the auto-update code, which distribution packagers can then enable during their package build an have a resulting binary that will not try to overwrite system-wide installed files.

**Comment by kozec** [comment]
That's why I'm waiting on calmh's response in #154. I don't know what exactly is he doing to transform syncthing source to .deb package, but I believe it would be best to do same thing, especially if we are going to put result to same repository, probably through same build system.

That's why I tried to mimic what `build.go -deb` does.

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
